import type { StorageProfile, StorageProfileDetail } from './types';

/**
 * 보관함 목업 프로필 데이터 (10건)
 */
export const MOCK_STORAGE_PROFILES: StorageProfile[] = [
  {
    id: 1,
    name: '박실명',
    age: 28,
    location: '경기도 안양시',
    job: '뷰티마케터',
    cosmicType: 'star',
    imageUri: 'https://picsum.photos/seed/1/208/220',
    isFavorited: true,
  },
  {
    id: 2,
    name: '박실명',
    age: 28,
    location: '서울시 동안구',
    job: '모델',
    cosmicType: 'solar',
    imageUri: 'https://picsum.photos/seed/2/208/220',
    isFavorited: false,
  },
  {
    id: 3,
    name: '유나',
    age: 31,
    location: '부산 해운대구',
    job: '백엔드 개발자',
    cosmicType: 'luna',
    imageUri: 'https://picsum.photos/seed/3/208/220',
    isFavorited: true,
  },
  {
    id: 4,
    name: '안유진',
    age: 25,
    location: '대전 유성구',
    job: '보컬 트레이너',
    cosmicType: 'galaxy',
    imageUri: 'https://picsum.photos/seed/4/208/220',
    isFavorited: false,
  },
  {
    id: 5,
    name: '김서윤',
    age: 27,
    location: '서울 강남구',
    job: 'UX 디자이너',
    cosmicType: 'star',
    imageUri: 'https://picsum.photos/seed/5/208/220',
    isFavorited: true,
  },
  {
    id: 6,
    name: '이하은',
    age: 30,
    location: '인천 연수구',
    job: '프론트엔드 개발자',
    cosmicType: 'galaxy',
    imageUri: 'https://picsum.photos/seed/6/208/220',
    isFavorited: false,
  },
  {
    id: 7,
    name: '정민서',
    age: 26,
    location: '대구 수성구',
    job: '영상 편집자',
    cosmicType: 'solar',
    imageUri: 'https://picsum.photos/seed/7/208/220',
    isFavorited: true,
  },
  {
    id: 8,
    name: '최예린',
    age: 29,
    location: '광주 서구',
    job: '간호사',
    cosmicType: 'luna',
    imageUri: 'https://picsum.photos/seed/8/208/220',
    isFavorited: false,
  },
  {
    id: 9,
    name: '한소희',
    age: 24,
    location: '제주 제주시',
    job: '카페 매니저',
    cosmicType: 'star',
    imageUri: 'https://picsum.photos/seed/9/208/220',
    isFavorited: true,
  },
  {
    id: 10,
    name: '윤지우',
    age: 32,
    location: '세종시',
    job: '공무원',
    cosmicType: 'galaxy',
    imageUri: 'https://picsum.photos/seed/10/208/220',
    isFavorited: false,
  },
];

/**
 * 보관함 프로필 상세 목업 데이터
 * - MOCK_STORAGE_PROFILES 기반으로 상세 필드 추가
 */
export const MOCK_STORAGE_PROFILE_DETAILS: StorageProfileDetail[] = [
  {
    ...MOCK_STORAGE_PROFILES[0],
    interests: ['TRAVEL', 'FOOD', 'MUSIC', 'MOVIE'],
    commonInterests: ['TRAVEL', 'MUSIC'],
    bio: '여행과 음악을 좋아하는 뷰티마케터입니다 :)',
    region: 'GYEONGGI',
    subArea: '안양시',
    jobField: '뷰티마케터',
    tmiAnswers: [
      { questionId: 'q1', answer: '다른 친구를 부른다' },
      { questionId: 'q2', answer: '예상치 못한 꽃다발' },
    ],
    cosmicTypeDesc: '사랑이 시작되면 누구보다 빠르게 빛나는 사람',
  },
  {
    ...MOCK_STORAGE_PROFILES[1],
    interests: ['EXERCISE', 'SELF_DEV', 'CONCERT'],
    commonInterests: ['EXERCISE'],
    bio: '운동과 자기계발을 즐기는 모델입니다.',
    region: 'SEOUL',
    subArea: '동안구',
    jobField: '모델',
    tmiAnswers: [
      { questionId: 'q1', answer: '혼자만의 시간을 즐긴다' },
    ],
    cosmicTypeDesc: '서로를 존중하며 함께 성장하는 독립적인 연애',
  },
  {
    ...MOCK_STORAGE_PROFILES[2],
    interests: ['GAME', 'READING', 'MOVIE'],
    commonInterests: ['READING', 'MOVIE'],
    bio: '코딩과 독서를 좋아하는 개발자입니다.',
    region: 'BUSAN',
    subArea: '해운대구',
    jobField: '백엔드 개발자',
    tmiAnswers: [
      { questionId: 'q1', answer: '이유부터 궁금하다' },
      { questionId: 'q3', answer: '말보다 행동' },
    ],
    cosmicTypeDesc: '믿음과 배려로 오래 함께하는 잔잔한 연애',
  },
  {
    ...MOCK_STORAGE_PROFILES[3],
    interests: ['MUSIC', 'CONCERT', 'CAMPING'],
    commonInterests: [],
    bio: '음악이 삶의 전부인 보컬 트레이너입니다.',
    region: 'CHUNGCHEONG',
    subArea: '유성구',
    jobField: '보컬 트레이너',
    tmiAnswers: [],
    cosmicTypeDesc: '서로를 존중하며 함께 성장하는 독립적인 연애',
  },
];
