import type { StorageProfile } from './types';

/**
 * 보관함 목업 프로필 데이터 (10건)
 */
export const MOCK_STORAGE_PROFILES: StorageProfile[] = [
  {
    id: 1,
    name: '박실명',
    age: 28,
    location: '경기도 안양시',
    job: '뷰티마케터',
    cosmicType: 'star',
    imageUri: 'https://picsum.photos/seed/1/208/220',
    isFavorited: true,
  },
  {
    id: 2,
    name: '박실명',
    age: 28,
    location: '서울시 동안구',
    job: '모델',
    cosmicType: 'solar',
    imageUri: 'https://picsum.photos/seed/2/208/220',
    isFavorited: false,
  },
  {
    id: 3,
    name: '유나',
    age: 31,
    location: '부산 해운대구',
    job: '백엔드 개발자',
    cosmicType: 'luna',
    imageUri: 'https://picsum.photos/seed/3/208/220',
    isFavorited: true,
  },
  {
    id: 4,
    name: '안유진',
    age: 25,
    location: '대전 유성구',
    job: '보컬 트레이너',
    cosmicType: 'galaxy',
    imageUri: 'https://picsum.photos/seed/4/208/220',
    isFavorited: false,
  },
  {
    id: 5,
    name: '김서윤',
    age: 27,
    location: '서울 강남구',
    job: 'UX 디자이너',
    cosmicType: 'star',
    imageUri: 'https://picsum.photos/seed/5/208/220',
    isFavorited: true,
  },
  {
    id: 6,
    name: '이하은',
    age: 30,
    location: '인천 연수구',
    job: '프론트엔드 개발자',
    cosmicType: 'galaxy',
    imageUri: 'https://picsum.photos/seed/6/208/220',
    isFavorited: false,
  },
  {
    id: 7,
    name: '정민서',
    age: 26,
    location: '대구 수성구',
    job: '영상 편집자',
    cosmicType: 'solar',
    imageUri: 'https://picsum.photos/seed/7/208/220',
    isFavorited: true,
  },
  {
    id: 8,
    name: '최예린',
    age: 29,
    location: '광주 서구',
    job: '간호사',
    cosmicType: 'luna',
    imageUri: 'https://picsum.photos/seed/8/208/220',
    isFavorited: false,
  },
  {
    id: 9,
    name: '한소희',
    age: 24,
    location: '제주 제주시',
    job: '카페 매니저',
    cosmicType: 'star',
    imageUri: 'https://picsum.photos/seed/9/208/220',
    isFavorited: true,
  },
  {
    id: 10,
    name: '윤지우',
    age: 32,
    location: '세종시',
    job: '공무원',
    cosmicType: 'galaxy',
    imageUri: 'https://picsum.photos/seed/10/208/220',
    isFavorited: false,
  },
];
